#!/usr/bin/env python
import SocketServer
import time

players = {}

class Handler(SocketServer.BaseRequestHandler):
    def handle(self):
        global players

        data = eval(self.request[0].strip())
        socket = self.request[1]

        if not data[0] in players:
            print data

        players[data[0]] = data[1:]

        #time.sleep(.0166666)
        socket.sendto(str(players), self.client_address)

if __name__ == "__main__":
    addr = "0.0.0.0", 27013
    server = SocketServer.UDPServer(addr, Handler)
    server.serve_forever()
